export const ACCESS_TOKEN = 'Access_Token'
export const REFRESH_TOKEN = 'Refresh_Token'
export const USER_INFO = 'Login_Userinfo'
export const BUTTON_LIST = 'Button_List'
export const ROLE_LIST = 'Role_List'
export const FORM_CACHE = 'Form_Cache'