export const ACCESS_TOKEN = 'Access-Token'
export const USER_INFO = 'Login_Userinfo'
export const BUTTON_LIST = 'Button_List'
export const ROLE_LIST = 'Role_List'
export const FORM_CACHE = 'Form_Cache'
