// 浮动表单配置文件

export const otherComponentsFloat = [
  {
    __config__: {
      tagIcon: "表格",
      layout: "customTable",
      label: "表格",
      tag: "customEditTable",
      showLabel: true,
      span: 24,
      required: true,
    },
    row: 1,
    col: 3,
    selectedCol: -1,
    comment: "",
    columns: [
      {
        label: "列1",
        props: "col1",
        type: "input",
        required: true,
        options: [
          {
            label: "选项一",
            value: 1,
          },
          {
            label: "选项二",
            value: 2,
          },
        ],
        allowChar: false,
        precision: 0,
        min: undefined,
        max: undefined,
        isMobile: false,
        format: "yyyy-MM",
        "value-format": "yyyy-MM",
        dateType: "month",
        comment: "",
        filterable: false,
        multiple: false,
      },
      {
        label: "列2",
        props: "col2",
        type: "input",
        required: true,
        options: [
          {
            label: "选项一",
            value: 1,
          },
          {
            label: "选项二",
            value: 2,
          },
        ],
        allowChar: false,
        precision: 0,
        min: undefined,
        max: undefined,
        isMobile: false,
        format: "yyyy-MM",
        "value-format": "yyyy-MM",
        dateType: "month",
        comment: "",
        filterable: false,
        multiple: false,
      },
      {
        label: "列3",
        props: "col3",
        type: "input",
        required: true,
        options: [
          {
            label: "选项一",
            value: 1,
          },
          {
            label: "选项二",
            value: 2,
          },
        ],
        allowChar: false,
        precision: 0,
        min: undefined,
        max: undefined,
        isMobile: false,
        format: "yyyy-MM",
        "value-format": "yyyy-MM",
        dateType: "month",
        comment: "",
        filterable: false,
        multiple: false,
      },
    ],
  },
];
